import { CheckCircle2, ClipboardCheck, History, UserCheck } from "lucide-react";

type Report = { id: number; deviceCategory: string; browserFamily: string; issueType: string; osVersion: string | null; message: string; status: string; assignedReviewerUserId: number | null; createdAt: Date; updatedAt: Date };
type Reviewer = { id: number; name: string | null; email?: string | null; role: string };
type Event = { id?: number; feedbackId: number; event: string; note?: string | null; createdAt?: Date };

export function CompatibilityReviewPanel({ reports, reviewers, events, selectedId, pending, onSelect, onAssign, onDecide }: { reports: Report[]; reviewers: Reviewer[]; events: Event[]; selectedId: number | null; pending: boolean; onSelect: (id: number) => void; onAssign: (feedbackId: number, reviewerUserId: number) => void; onDecide: (feedbackId: number, event: "approved" | "changes-requested" | "rejected" | "closed") => void }) {
  const reviewerId = reviewers[0]?.id;
  return <section className="compatibility-review-panel panel" aria-labelledby="review-queue-title"><div className="panel-header"><div><div className="section-kicker"><ClipboardCheck size={13} /> Authorized staff / review governance</div><h2 id="review-queue-title">Review queue <span className="muted-slash">/</span> <span>{reports.length} submissions</span></h2></div><span className="small-pill"><UserCheck size={12} /> ADMIN ONLY</span></div><p>Assignments and decisions are recorded as audit events. This internal workflow does not certify devices or issue external approvals.</p>{reports.length ? <div className="review-queue">{reports.map((report) => <article key={report.id} className={`review-report review-${report.status}`}><div className="review-report-main"><span className="review-status">{report.status.replace("-", " ")}</span><strong>{report.deviceCategory.toUpperCase()} · {report.browserFamily.toUpperCase()} · {report.issueType.toUpperCase()}</strong><small>{report.osVersion || "OS version not provided"} · {new Date(report.createdAt).toLocaleString()}</small><p>{report.message}</p></div><div className="review-report-actions">{reviewerId && <button className="outline-button outline-small" disabled={pending} onClick={() => onAssign(report.id, reviewerId)}><UserCheck size={13} /> Assign</button>}<button className="outline-button outline-small" disabled={pending} onClick={() => onDecide(report.id, "approved")}><CheckCircle2 size={13} /> Approve</button><button className="outline-button outline-small" disabled={pending} onClick={() => onDecide(report.id, "changes-requested")}>Changes</button><button className="outline-button outline-small" disabled={pending} onClick={() => onDecide(report.id, "closed")}>Close</button><button className="text-button" onClick={() => onSelect(report.id)}><History size={13} /> History</button></div></article>)}</div> : <div className="asset-empty"><span>No compatibility submissions are awaiting staff review.</span></div>}{selectedId !== null && <div className="review-history"><div><span className="section-kicker"><History size={13} /> Approval history / submission #{selectedId}</span><strong>Recorded review events</strong></div>{events.length ? events.map((event, index) => <div key={`${event.feedbackId}-${event.event}-${index}`}><span>{event.event}</span><small>{event.note || "No note recorded"} · {event.createdAt ? new Date(event.createdAt).toLocaleString() : "recorded"}</small></div>) : <small>No review events have been recorded yet.</small>}</div>}</section>;
}
