import { useState } from "react";
import { AlertTriangle, Send, ShieldCheck } from "lucide-react";

type Draft = { deviceCategory: "phone" | "tablet" | "desktop" | "laptop" | "other"; browserFamily: "safari" | "chrome" | "edge" | "firefox" | "other"; issueType: "audio-output" | "playback" | "layout" | "accessibility" | "other"; osVersion: string; message: string; website: string };
const initial: Draft = { deviceCategory: "phone", browserFamily: "safari", issueType: "audio-output", osVersion: "", message: "", website: "" };

export function CompatibilityFeedbackPanel({ pending, onSubmit }: { pending: boolean; onSubmit: (draft: Draft) => Promise<void> }) {
  const [draft, setDraft] = useState<Draft>(initial);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); await onSubmit(draft); setDraft(initial); };
  return <section className="compatibility-feedback-panel panel" aria-labelledby="compatibility-feedback-title"><div className="panel-header"><div><div className="section-kicker"><AlertTriangle size={13} /> Device compatibility / feedback</div><h2 id="compatibility-feedback-title">Report an issue <span className="muted-slash">/</span> <span>help us improve playback</span></h2></div><span className="small-pill"><ShieldCheck size={12} /> MINIMUM DATA</span></div><p>Tell us what happened on your device. Please do not include passwords, keys, payment data, serial numbers, names, email addresses, or precise device identifiers.</p><form onSubmit={submit} className="compatibility-form"><label>Device category<select value={draft.deviceCategory} onChange={(event) => setDraft({ ...draft, deviceCategory: event.target.value as Draft["deviceCategory"] })}><option value="phone">Phone</option><option value="tablet">Tablet</option><option value="laptop">Laptop</option><option value="desktop">Desktop</option><option value="other">Other</option></select></label><label>Browser family<select value={draft.browserFamily} onChange={(event) => setDraft({ ...draft, browserFamily: event.target.value as Draft["browserFamily"] })}><option value="safari">Safari</option><option value="chrome">Chrome</option><option value="edge">Edge</option><option value="firefox">Firefox</option><option value="other">Other</option></select></label><label>Issue type<select value={draft.issueType} onChange={(event) => setDraft({ ...draft, issueType: event.target.value as Draft["issueType"] })}><option value="audio-output">Audio output</option><option value="playback">Playback</option><option value="layout">Layout</option><option value="accessibility">Accessibility</option><option value="other">Other</option></select></label><label>OS version <em>optional</em><input value={draft.osVersion} maxLength={80} onChange={(event) => setDraft({ ...draft, osVersion: event.target.value })} placeholder="For example: iOS 17" /></label><label className="compatibility-message">What happened?<textarea required minLength={12} maxLength={2000} value={draft.message} onChange={(event) => setDraft({ ...draft, message: event.target.value })} placeholder="Describe the action, the expected result, and what happened instead." /></label><input className="contact-honeypot" tabIndex={-1} autoComplete="off" value={draft.website} onChange={(event) => setDraft({ ...draft, website: event.target.value })} aria-label="Website" /><button className="solid-button" disabled={pending}><Send size={14} /> {pending ? "Sending…" : "Send compatibility feedback"}</button></form></section>;
}
