import { Activity, Download, Radio, RotateCcw, ShieldCheck, SlidersHorizontal } from "lucide-react";
import { useMemo, useState } from "react";
import { getLocalFlashingScaffold, localFlashingScaffoldArchives, type LocalFlashingScaffoldId } from "@shared/localFlashingScaffolds";
import "./LocalPracticeReceiverPanel.css";

type PracticeState = "idle" | "armed" | "listening" | "pad-cue";

export function LocalPracticeReceiverPanel({ onRoutePracticeAudio, onPracticePad }: { onRoutePracticeAudio: () => void; onPracticePad: () => void }) {
  const [selectedId, setSelectedId] = useState<LocalFlashingScaffoldId>("esp32");
  const [practiceState, setPracticeState] = useState<PracticeState>("idle");
  const scaffold = getLocalFlashingScaffold(selectedId);
  const status = useMemo(() => ({ idle: ["READY", "Choose a local scaffold or start a browser practice cue."], armed: ["PRACTICE ARMED", "Virtual receiver state is ready; no physical board or RF channel is connected."], listening: ["AUDIO CUE ROUTED", "A browser-only practice cue is routed through the PARKWAY transport and stereo path."], "pad-cue": ["PAD FEEDBACK", "A browser practice pad state is active; no instrument hardware is being controlled."] } as const)[practiceState], [practiceState]);

  return <section className="local-practice-panel" aria-labelledby="local-practice-title"><div className="local-practice-head"><div><span><Radio size={13} /> Virtual practice receiver / browser-local</span><h3 id="local-practice-title">Hands-on local build and practice</h3><p>Download a scaffold for a user-owned board, rehearse source and instrument-cue states here, then build and flash only through your local toolchain.</p></div><span className="small-pill"><ShieldCheck size={12} /> NO DEVICE LINK</span></div><div className="scaffold-download-grid">{localFlashingScaffoldArchives.map((item) => <article key={item.id} className={`scaffold-download-card ${selectedId === item.id ? "is-selected" : ""}`}><button className="scaffold-select" aria-pressed={selectedId === item.id} onClick={() => { setSelectedId(item.id); setPracticeState("armed"); }}><span>{item.id.toUpperCase()} / ZIP</span><strong>{item.label}</strong><small>{item.sourceLabel}</small></button><a className="outline-button outline-small" href={item.archiveUrl} download={item.filename}><Download size={13} /> Download ZIP</a></article>)}</div><div className="practice-console"><div className="practice-status"><Activity size={18} /><div><span>{status[0]}</span><strong>{scaffold.label}</strong><small>{status[1]}</small></div><button className="icon-button" aria-label="Reset practice receiver" onClick={() => setPracticeState("idle")}><RotateCcw size={14} /></button></div><div className="practice-signal-rail" aria-label={`Practice status ${practiceState}`}><i className={practiceState === "listening" ? "is-live" : ""} /><i className={practiceState === "pad-cue" ? "is-live" : ""} /><i className={practiceState === "armed" ? "is-live" : ""} /><i className={practiceState !== "idle" ? "is-live" : ""} /><i className={practiceState === "listening" ? "is-live" : ""} /><i className={practiceState === "pad-cue" ? "is-live" : ""} /></div><div className="practice-actions"><button className="solid-button" onClick={() => { setPracticeState("listening"); onRoutePracticeAudio(); }}><Radio size={13} /> Route browser audio cue</button><button className="outline-button" onClick={() => { setPracticeState("pad-cue"); onPracticePad(); }}><SlidersHorizontal size={13} /> Trigger practice pad feedback</button><button className="outline-button" onClick={() => setPracticeState("armed")}><Activity size={13} /> Arm local build checklist</button></div></div><div className="scaffold-local-note"><ShieldCheck size={14} /><span><strong>Local flashing remains a separate, explicit action.</strong> {scaffold.localStep} The ZIP does not contain credentials, RF settings, serial numbers, or remote-control code.</span></div></section>;
}
